linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - ineffassign
    - staticcheck
    - unused
    - govet
    - misspell
    # Disabled - too noisy for existing codebase:
    # - gosec     # Many false positives (G104, G304, G301, etc.)
    # - errcheck  # Requires extensive refactoring
    # - gocritic  # Style preferences
    # - revive    # Doc comment requirements

linters-settings:
  goimports:
    local-prefixes: github.com/dotcommander/zai

  govet:
    enable-all: true
    disable:
      - fieldalignment # Micro-optimization, not worth the churn
      - shadow # Common pattern with err

run:
  timeout: 5m
  tests: true
  build-tags: []

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
