linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - gosec
    - ineffassign
    - staticcheck
    - unused
    - varcheck
    - errcheck
    - govet
    - misspell
    - gocritic
    - revive

linters-settings:
  goimports:
    local-prefixes: zai

  govet:
    enable-all: true

  errcheck:
    check-type-assertions: true
    check-blank: true

  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: indent-error-flow
        severity: warning

run:
  timeout: 5m
  tests: true
  build-tags: []

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
